# Development

## Local Development

A `run-local.sh` script is provided that will apply CRD definitions,
setup the local virtual environment, and run the operator.

To run tests just use `run-test.sh` in another terminal.

## Development OpenShift Build

The OpenShift build process is a bit slower for development but has the advantage of being a bit closer to a normal deployment of poolboy.
It is often best to iterate development using `odo` and also test with an OpenShift build and deployment prior to opening a pull request.

. Create a project for development using `oc`:
+
--------------------------------------
oc new-project user-namespace-operator
--------------------------------------

. Process OpenShift build template to create BuildConfig and ImageStream:
+
---------------------------------------------------------
oc process --local -f build-template.yaml | oc apply -f -
---------------------------------------------------------

. Build user-namespace-operator image from local source:
+
------------------------------------------------------------
oc start-build user-namespace-operator --from-dir=. --follow
------------------------------------------------------------

. Deploy user-namespace-operator from build image
+
--------------------------------------------------------------------------------
helm template helm \
--include-crds \
--set namespace.create=false \
--set namespace.name=user-namespace-operator \
--set=image.tagOverride=- \
--set=image.repository=$(oc get imagestream user-namespace-operator -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}') \
| oc apply -f -
--------------------------------------------------------------------------------

. Run tests:
+
-----------------------------------
ansible-playbook test/playbook.yaml
-----------------------------------

. Cleanup
+
Remove resources created from the helm template:
+
---------------------------------------------
helm template helm \
--set namespace.create=false \
--set namespace.name=user-namespace-operator \
| oc delete -f -
---------------------------------------------
+
Remove BuildConfig and ImageStream:
+
----------------------------------------------------------
oc process --local -f build-template.yaml | oc delete -f -
----------------------------------------------------------
